pipeline {
    agent any

    environment {
        IMAGE_NAME = 'nodejs-app'
        IMAGE_TAG = "${BUILD_NUMBER}"         // Use Jenkins build number as image tag
        REGISTRY = 'pradeeshan'
        FULL_IMAGE = "${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git 'https://your-repo-url.git'   // Replace with your actual repo
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $FULL_IMAGE .'
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push $FULL_IMAGE'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                kubectl set image deployment/nodejs-deployment nodejs-container=$FULL_IMAGE --record
                kubectl rollout status deployment/nodejs-deployment
                '''
            }
        }
    }
}
